-- Import av 15 års historik (2012-2026) från Run_As_You_Are__Resultat.xlsx
--
-- Lägg till en unik-constraint på runners.name så vi kan upsert:a säkert
-- (annars riskerar ett omkört av denna migration att skapa dubbletter,
-- och den befintliga testraden för "Daniel Solving" från röktestet
-- slås ihop med den riktiga importraden istället för att bli en dubblett).
alter table runners add constraint runners_name_key unique (name);

-- Upplagor 2012-2026 (2027 finns redan - skapad under röktestet).
insert into editions (year) values
  (2012),
  (2013),
  (2014),
  (2015),
  (2016),
  (2017),
  (2018),
  (2019),
  (2020),
  (2021),
  (2022),
  (2023),
  (2024),
  (2025),
  (2026)
on conflict (year) do nothing;

-- Löpare: namn + antal gånger de var värd (stjärnorna i originalarket).
insert into runners (name, host_count) values
  ('Daniel Solving', 6),
  ('Andreas Olsson', 2),
  ('Björn Stråhle', 0),
  ('Emil Svedung', 1),
  ('Jonas Zackrisson', 1),
  ('Erik Edvardsson', 3),
  ('Sebastian Sintorn', 2),
  ('Rasmus Borgvall', 0),
  ('Jonas Gernandt', 0),
  ('Joakim Andrèasson', 0),
  ('Niclas Norlèn', 0),
  ('Filip Obbel', 0),
  ('Patrik Gälman', 0),
  ('Gabriel Bergqvist', 0),
  ('Magnus Sandén', 0),
  ('Daniel Börjesson', 0),
  ('Johan Jörstun', 0)
on conflict (name) do update set host_count = excluded.host_count;

-- Resultat per löpare och år.
-- NI/DNR/DNC: bara status, ingen placering (appens egna scoring-motor
--   räknar själv ut "sist plus 2/4" från samma års faktiska antal löpare).
-- Allt annat (inklusive 2015 där vi saknade tidtagning, och Andreas
--   DNF 2021): riktig placering, ingen tid.
insert into results (edition_id, runner_id, placering, status, finish_time_sec) values
  ((select id from editions where year = 2012), (select id from runners where name = 'Daniel Solving'), 2, null, 3289),
  ((select id from editions where year = 2013), (select id from runners where name = 'Daniel Solving'), 2, null, 3231),
  ((select id from editions where year = 2014), (select id from runners where name = 'Daniel Solving'), null, 'DNR', null),
  ((select id from editions where year = 2015), (select id from runners where name = 'Daniel Solving'), 1, null, 3277),
  ((select id from editions where year = 2016), (select id from runners where name = 'Daniel Solving'), 2, null, 2580),
  ((select id from editions where year = 2017), (select id from runners where name = 'Daniel Solving'), null, 'DNR', null),
  ((select id from editions where year = 2018), (select id from runners where name = 'Daniel Solving'), 1, null, 2775),
  ((select id from editions where year = 2019), (select id from runners where name = 'Daniel Solving'), 3, null, 3031),
  ((select id from editions where year = 2020), (select id from runners where name = 'Daniel Solving'), 1, null, 2518),
  ((select id from editions where year = 2021), (select id from runners where name = 'Daniel Solving'), 3, null, 2905),
  ((select id from editions where year = 2022), (select id from runners where name = 'Daniel Solving'), 2, null, 3080),
  ((select id from editions where year = 2023), (select id from runners where name = 'Daniel Solving'), 3, null, 2969),
  ((select id from editions where year = 2024), (select id from runners where name = 'Daniel Solving'), 2, null, 2904),
  ((select id from editions where year = 2025), (select id from runners where name = 'Daniel Solving'), 5, null, 3280),
  ((select id from editions where year = 2026), (select id from runners where name = 'Daniel Solving'), 4, null, 3279),
  ((select id from editions where year = 2012), (select id from runners where name = 'Andreas Olsson'), 3, null, 3387),
  ((select id from editions where year = 2013), (select id from runners where name = 'Andreas Olsson'), 6, null, 3784),
  ((select id from editions where year = 2014), (select id from runners where name = 'Andreas Olsson'), 2, null, 3372),
  ((select id from editions where year = 2015), (select id from runners where name = 'Andreas Olsson'), 2, null, null),
  ((select id from editions where year = 2016), (select id from runners where name = 'Andreas Olsson'), 3, null, 2686),
  ((select id from editions where year = 2017), (select id from runners where name = 'Andreas Olsson'), 3, null, 2676),
  ((select id from editions where year = 2018), (select id from runners where name = 'Andreas Olsson'), 3, null, 3025),
  ((select id from editions where year = 2019), (select id from runners where name = 'Andreas Olsson'), 4, null, 3163),
  ((select id from editions where year = 2020), (select id from runners where name = 'Andreas Olsson'), null, 'DNC', null),
  ((select id from editions where year = 2021), (select id from runners where name = 'Andreas Olsson'), 6, null, null),
  ((select id from editions where year = 2022), (select id from runners where name = 'Andreas Olsson'), 4, null, 3440),
  ((select id from editions where year = 2023), (select id from runners where name = 'Andreas Olsson'), 4, null, 3152),
  ((select id from editions where year = 2024), (select id from runners where name = 'Andreas Olsson'), 4, null, 3265),
  ((select id from editions where year = 2025), (select id from runners where name = 'Andreas Olsson'), 4, null, 3193),
  ((select id from editions where year = 2026), (select id from runners where name = 'Andreas Olsson'), 6, null, 3465),
  ((select id from editions where year = 2012), (select id from runners where name = 'Björn Stråhle'), null, 'NI', null),
  ((select id from editions where year = 2013), (select id from runners where name = 'Björn Stråhle'), null, 'NI', null),
  ((select id from editions where year = 2014), (select id from runners where name = 'Björn Stråhle'), null, 'NI', null),
  ((select id from editions where year = 2015), (select id from runners where name = 'Björn Stråhle'), null, 'NI', null),
  ((select id from editions where year = 2016), (select id from runners where name = 'Björn Stråhle'), null, 'NI', null),
  ((select id from editions where year = 2017), (select id from runners where name = 'Björn Stråhle'), null, 'NI', null),
  ((select id from editions where year = 2018), (select id from runners where name = 'Björn Stråhle'), 4, null, 3087),
  ((select id from editions where year = 2019), (select id from runners where name = 'Björn Stråhle'), 5, null, 3324),
  ((select id from editions where year = 2020), (select id from runners where name = 'Björn Stråhle'), 2, null, 2560),
  ((select id from editions where year = 2021), (select id from runners where name = 'Björn Stråhle'), 5, null, 2990),
  ((select id from editions where year = 2022), (select id from runners where name = 'Björn Stråhle'), 5, null, 3500),
  ((select id from editions where year = 2023), (select id from runners where name = 'Björn Stråhle'), 5, null, 3239),
  ((select id from editions where year = 2024), (select id from runners where name = 'Björn Stråhle'), 3, null, 3082),
  ((select id from editions where year = 2025), (select id from runners where name = 'Björn Stråhle'), 3, null, 2911),
  ((select id from editions where year = 2026), (select id from runners where name = 'Björn Stråhle'), 3, null, 3116),
  ((select id from editions where year = 2012), (select id from runners where name = 'Emil Svedung'), null, 'NI', null),
  ((select id from editions where year = 2013), (select id from runners where name = 'Emil Svedung'), null, 'NI', null),
  ((select id from editions where year = 2014), (select id from runners where name = 'Emil Svedung'), null, 'NI', null),
  ((select id from editions where year = 2015), (select id from runners where name = 'Emil Svedung'), null, 'NI', null),
  ((select id from editions where year = 2016), (select id from runners where name = 'Emil Svedung'), null, 'NI', null),
  ((select id from editions where year = 2017), (select id from runners where name = 'Emil Svedung'), null, 'NI', null),
  ((select id from editions where year = 2018), (select id from runners where name = 'Emil Svedung'), null, 'DNC', null),
  ((select id from editions where year = 2019), (select id from runners where name = 'Emil Svedung'), 1, null, 2730),
  ((select id from editions where year = 2020), (select id from runners where name = 'Emil Svedung'), null, 'DNC', null),
  ((select id from editions where year = 2021), (select id from runners where name = 'Emil Svedung'), 1, null, 2542),
  ((select id from editions where year = 2022), (select id from runners where name = 'Emil Svedung'), 1, null, 2772),
  ((select id from editions where year = 2023), (select id from runners where name = 'Emil Svedung'), 1, null, 2672),
  ((select id from editions where year = 2024), (select id from runners where name = 'Emil Svedung'), null, 'DNC', null),
  ((select id from editions where year = 2025), (select id from runners where name = 'Emil Svedung'), 1, null, 2451),
  ((select id from editions where year = 2026), (select id from runners where name = 'Emil Svedung'), 1, null, 2697),
  ((select id from editions where year = 2012), (select id from runners where name = 'Jonas Zackrisson'), null, 'NI', null),
  ((select id from editions where year = 2013), (select id from runners where name = 'Jonas Zackrisson'), null, 'NI', null),
  ((select id from editions where year = 2014), (select id from runners where name = 'Jonas Zackrisson'), null, 'NI', null),
  ((select id from editions where year = 2015), (select id from runners where name = 'Jonas Zackrisson'), null, 'NI', null),
  ((select id from editions where year = 2016), (select id from runners where name = 'Jonas Zackrisson'), null, 'NI', null),
  ((select id from editions where year = 2017), (select id from runners where name = 'Jonas Zackrisson'), null, 'NI', null),
  ((select id from editions where year = 2018), (select id from runners where name = 'Jonas Zackrisson'), null, 'NI', null),
  ((select id from editions where year = 2019), (select id from runners where name = 'Jonas Zackrisson'), null, 'NI', null),
  ((select id from editions where year = 2020), (select id from runners where name = 'Jonas Zackrisson'), null, 'NI', null),
  ((select id from editions where year = 2021), (select id from runners where name = 'Jonas Zackrisson'), 2, null, 2677),
  ((select id from editions where year = 2022), (select id from runners where name = 'Jonas Zackrisson'), null, 'DNC', null),
  ((select id from editions where year = 2023), (select id from runners where name = 'Jonas Zackrisson'), 2, null, 2816),
  ((select id from editions where year = 2024), (select id from runners where name = 'Jonas Zackrisson'), 1, null, 2796),
  ((select id from editions where year = 2025), (select id from runners where name = 'Jonas Zackrisson'), 2, null, 2532),
  ((select id from editions where year = 2026), (select id from runners where name = 'Jonas Zackrisson'), 2, null, 2844),
  ((select id from editions where year = 2012), (select id from runners where name = 'Erik Edvardsson'), 5, null, 3590),
  ((select id from editions where year = 2013), (select id from runners where name = 'Erik Edvardsson'), 3, null, 3387),
  ((select id from editions where year = 2014), (select id from runners where name = 'Erik Edvardsson'), null, 'DNC', null),
  ((select id from editions where year = 2015), (select id from runners where name = 'Erik Edvardsson'), 3, null, null),
  ((select id from editions where year = 2016), (select id from runners where name = 'Erik Edvardsson'), 5, null, 2877),
  ((select id from editions where year = 2017), (select id from runners where name = 'Erik Edvardsson'), 4, null, 2754),
  ((select id from editions where year = 2018), (select id from runners where name = 'Erik Edvardsson'), 6, null, 3421),
  ((select id from editions where year = 2019), (select id from runners where name = 'Erik Edvardsson'), 6, null, 3741),
  ((select id from editions where year = 2020), (select id from runners where name = 'Erik Edvardsson'), 4, null, 2940),
  ((select id from editions where year = 2021), (select id from runners where name = 'Erik Edvardsson'), null, 'DNC', null),
  ((select id from editions where year = 2022), (select id from runners where name = 'Erik Edvardsson'), null, 'DNR', null),
  ((select id from editions where year = 2023), (select id from runners where name = 'Erik Edvardsson'), null, 'DNR', null),
  ((select id from editions where year = 2024), (select id from runners where name = 'Erik Edvardsson'), 7, null, 3780),
  ((select id from editions where year = 2025), (select id from runners where name = 'Erik Edvardsson'), null, 'DNR', null),
  ((select id from editions where year = 2026), (select id from runners where name = 'Erik Edvardsson'), 7, null, 4154),
  ((select id from editions where year = 2012), (select id from runners where name = 'Sebastian Sintorn'), 4, null, 3550),
  ((select id from editions where year = 2013), (select id from runners where name = 'Sebastian Sintorn'), null, 'DNC', null),
  ((select id from editions where year = 2014), (select id from runners where name = 'Sebastian Sintorn'), 3, null, 3818),
  ((select id from editions where year = 2015), (select id from runners where name = 'Sebastian Sintorn'), null, 'DNC', null),
  ((select id from editions where year = 2016), (select id from runners where name = 'Sebastian Sintorn'), 4, null, 2814),
  ((select id from editions where year = 2017), (select id from runners where name = 'Sebastian Sintorn'), 5, null, 3043),
  ((select id from editions where year = 2018), (select id from runners where name = 'Sebastian Sintorn'), 5, null, 3157),
  ((select id from editions where year = 2019), (select id from runners where name = 'Sebastian Sintorn'), null, 'DNR', null),
  ((select id from editions where year = 2020), (select id from runners where name = 'Sebastian Sintorn'), 3, null, 2589),
  ((select id from editions where year = 2021), (select id from runners where name = 'Sebastian Sintorn'), 4, null, 2975),
  ((select id from editions where year = 2022), (select id from runners where name = 'Sebastian Sintorn'), 6, null, 3528),
  ((select id from editions where year = 2023), (select id from runners where name = 'Sebastian Sintorn'), null, 'DNR', null),
  ((select id from editions where year = 2024), (select id from runners where name = 'Sebastian Sintorn'), null, 'DNC', null),
  ((select id from editions where year = 2025), (select id from runners where name = 'Sebastian Sintorn'), null, 'DNR', null),
  ((select id from editions where year = 2026), (select id from runners where name = 'Sebastian Sintorn'), 5, null, 3350),
  ((select id from editions where year = 2012), (select id from runners where name = 'Rasmus Borgvall'), 1, null, 3280),
  ((select id from editions where year = 2013), (select id from runners where name = 'Rasmus Borgvall'), 1, null, 3212),
  ((select id from editions where year = 2014), (select id from runners where name = 'Rasmus Borgvall'), 1, null, 3013),
  ((select id from editions where year = 2015), (select id from runners where name = 'Rasmus Borgvall'), null, 'DNC', null),
  ((select id from editions where year = 2016), (select id from runners where name = 'Rasmus Borgvall'), null, 'DNC', null),
  ((select id from editions where year = 2017), (select id from runners where name = 'Rasmus Borgvall'), 1, null, 2310),
  ((select id from editions where year = 2018), (select id from runners where name = 'Rasmus Borgvall'), null, 'DNC', null),
  ((select id from editions where year = 2019), (select id from runners where name = 'Rasmus Borgvall'), null, 'DNC', null),
  ((select id from editions where year = 2020), (select id from runners where name = 'Rasmus Borgvall'), null, 'DNC', null),
  ((select id from editions where year = 2021), (select id from runners where name = 'Rasmus Borgvall'), null, 'DNC', null),
  ((select id from editions where year = 2022), (select id from runners where name = 'Rasmus Borgvall'), null, 'DNC', null),
  ((select id from editions where year = 2023), (select id from runners where name = 'Rasmus Borgvall'), null, 'DNC', null),
  ((select id from editions where year = 2024), (select id from runners where name = 'Rasmus Borgvall'), null, 'DNC', null),
  ((select id from editions where year = 2025), (select id from runners where name = 'Rasmus Borgvall'), null, 'DNC', null),
  ((select id from editions where year = 2026), (select id from runners where name = 'Rasmus Borgvall'), null, 'DNC', null),
  ((select id from editions where year = 2012), (select id from runners where name = 'Jonas Gernandt'), null, 'NI', null),
  ((select id from editions where year = 2013), (select id from runners where name = 'Jonas Gernandt'), null, 'NI', null),
  ((select id from editions where year = 2014), (select id from runners where name = 'Jonas Gernandt'), null, 'NI', null),
  ((select id from editions where year = 2015), (select id from runners where name = 'Jonas Gernandt'), null, 'NI', null),
  ((select id from editions where year = 2016), (select id from runners where name = 'Jonas Gernandt'), 1, null, 2481),
  ((select id from editions where year = 2017), (select id from runners where name = 'Jonas Gernandt'), 2, null, 2516),
  ((select id from editions where year = 2018), (select id from runners where name = 'Jonas Gernandt'), 2, null, 2785),
  ((select id from editions where year = 2019), (select id from runners where name = 'Jonas Gernandt'), null, 'DNC', null),
  ((select id from editions where year = 2020), (select id from runners where name = 'Jonas Gernandt'), null, 'DNC', null),
  ((select id from editions where year = 2021), (select id from runners where name = 'Jonas Gernandt'), null, 'DNC', null),
  ((select id from editions where year = 2022), (select id from runners where name = 'Jonas Gernandt'), null, 'DNC', null),
  ((select id from editions where year = 2023), (select id from runners where name = 'Jonas Gernandt'), null, 'DNC', null),
  ((select id from editions where year = 2024), (select id from runners where name = 'Jonas Gernandt'), null, 'DNC', null),
  ((select id from editions where year = 2025), (select id from runners where name = 'Jonas Gernandt'), null, 'DNC', null),
  ((select id from editions where year = 2026), (select id from runners where name = 'Jonas Gernandt'), null, 'DNC', null),
  ((select id from editions where year = 2012), (select id from runners where name = 'Joakim Andrèasson'), null, 'NI', null),
  ((select id from editions where year = 2013), (select id from runners where name = 'Joakim Andrèasson'), null, 'NI', null),
  ((select id from editions where year = 2014), (select id from runners where name = 'Joakim Andrèasson'), null, 'NI', null),
  ((select id from editions where year = 2015), (select id from runners where name = 'Joakim Andrèasson'), null, 'NI', null),
  ((select id from editions where year = 2016), (select id from runners where name = 'Joakim Andrèasson'), null, 'NI', null),
  ((select id from editions where year = 2017), (select id from runners where name = 'Joakim Andrèasson'), null, 'NI', null),
  ((select id from editions where year = 2018), (select id from runners where name = 'Joakim Andrèasson'), null, 'NI', null),
  ((select id from editions where year = 2019), (select id from runners where name = 'Joakim Andrèasson'), null, 'NI', null),
  ((select id from editions where year = 2020), (select id from runners where name = 'Joakim Andrèasson'), null, 'NI', null),
  ((select id from editions where year = 2021), (select id from runners where name = 'Joakim Andrèasson'), null, 'NI', null),
  ((select id from editions where year = 2022), (select id from runners where name = 'Joakim Andrèasson'), null, 'NI', null),
  ((select id from editions where year = 2023), (select id from runners where name = 'Joakim Andrèasson'), 9, null, null),
  ((select id from editions where year = 2024), (select id from runners where name = 'Joakim Andrèasson'), null, 'NI', null),
  ((select id from editions where year = 2025), (select id from runners where name = 'Joakim Andrèasson'), null, 'NI', null),
  ((select id from editions where year = 2026), (select id from runners where name = 'Joakim Andrèasson'), 8, null, 4745),
  ((select id from editions where year = 2012), (select id from runners where name = 'Niclas Norlèn'), null, 'NI', null),
  ((select id from editions where year = 2013), (select id from runners where name = 'Niclas Norlèn'), null, 'NI', null),
  ((select id from editions where year = 2014), (select id from runners where name = 'Niclas Norlèn'), null, 'NI', null),
  ((select id from editions where year = 2015), (select id from runners where name = 'Niclas Norlèn'), null, 'NI', null),
  ((select id from editions where year = 2016), (select id from runners where name = 'Niclas Norlèn'), null, 'NI', null),
  ((select id from editions where year = 2017), (select id from runners where name = 'Niclas Norlèn'), null, 'NI', null),
  ((select id from editions where year = 2018), (select id from runners where name = 'Niclas Norlèn'), null, 'NI', null),
  ((select id from editions where year = 2019), (select id from runners where name = 'Niclas Norlèn'), null, 'NI', null),
  ((select id from editions where year = 2020), (select id from runners where name = 'Niclas Norlèn'), null, 'NI', null),
  ((select id from editions where year = 2021), (select id from runners where name = 'Niclas Norlèn'), null, 'NI', null),
  ((select id from editions where year = 2022), (select id from runners where name = 'Niclas Norlèn'), null, 'NI', null),
  ((select id from editions where year = 2023), (select id from runners where name = 'Niclas Norlèn'), 9, null, null),
  ((select id from editions where year = 2024), (select id from runners where name = 'Niclas Norlèn'), 5, null, 3329),
  ((select id from editions where year = 2025), (select id from runners where name = 'Niclas Norlèn'), null, 'DNC', null),
  ((select id from editions where year = 2026), (select id from runners where name = 'Niclas Norlèn'), null, 'DNC', null),
  ((select id from editions where year = 2012), (select id from runners where name = 'Filip Obbel'), null, 'NI', null),
  ((select id from editions where year = 2013), (select id from runners where name = 'Filip Obbel'), null, 'NI', null),
  ((select id from editions where year = 2014), (select id from runners where name = 'Filip Obbel'), null, 'NI', null),
  ((select id from editions where year = 2015), (select id from runners where name = 'Filip Obbel'), null, 'NI', null),
  ((select id from editions where year = 2016), (select id from runners where name = 'Filip Obbel'), null, 'NI', null),
  ((select id from editions where year = 2017), (select id from runners where name = 'Filip Obbel'), null, 'NI', null),
  ((select id from editions where year = 2018), (select id from runners where name = 'Filip Obbel'), 7, null, 3510),
  ((select id from editions where year = 2019), (select id from runners where name = 'Filip Obbel'), null, 'DNC', null),
  ((select id from editions where year = 2020), (select id from runners where name = 'Filip Obbel'), null, 'DNC', null),
  ((select id from editions where year = 2021), (select id from runners where name = 'Filip Obbel'), null, 'DNC', null),
  ((select id from editions where year = 2022), (select id from runners where name = 'Filip Obbel'), 3, null, 3250),
  ((select id from editions where year = 2023), (select id from runners where name = 'Filip Obbel'), null, 'DNC', null),
  ((select id from editions where year = 2024), (select id from runners where name = 'Filip Obbel'), 6, null, 3544),
  ((select id from editions where year = 2025), (select id from runners where name = 'Filip Obbel'), null, 'DNC', null),
  ((select id from editions where year = 2026), (select id from runners where name = 'Filip Obbel'), null, 'DNC', null),
  ((select id from editions where year = 2012), (select id from runners where name = 'Patrik Gälman'), null, 'NI', null),
  ((select id from editions where year = 2013), (select id from runners where name = 'Patrik Gälman'), null, 'NI', null),
  ((select id from editions where year = 2014), (select id from runners where name = 'Patrik Gälman'), null, 'NI', null),
  ((select id from editions where year = 2015), (select id from runners where name = 'Patrik Gälman'), null, 'NI', null),
  ((select id from editions where year = 2016), (select id from runners where name = 'Patrik Gälman'), null, 'NI', null),
  ((select id from editions where year = 2017), (select id from runners where name = 'Patrik Gälman'), null, 'NI', null),
  ((select id from editions where year = 2018), (select id from runners where name = 'Patrik Gälman'), null, 'NI', null),
  ((select id from editions where year = 2019), (select id from runners where name = 'Patrik Gälman'), 2, null, 2897),
  ((select id from editions where year = 2020), (select id from runners where name = 'Patrik Gälman'), null, 'DNC', null),
  ((select id from editions where year = 2021), (select id from runners where name = 'Patrik Gälman'), null, 'DNC', null),
  ((select id from editions where year = 2022), (select id from runners where name = 'Patrik Gälman'), null, 'DNC', null),
  ((select id from editions where year = 2023), (select id from runners where name = 'Patrik Gälman'), null, 'DNC', null),
  ((select id from editions where year = 2024), (select id from runners where name = 'Patrik Gälman'), null, 'DNC', null),
  ((select id from editions where year = 2025), (select id from runners where name = 'Patrik Gälman'), null, 'DNC', null),
  ((select id from editions where year = 2026), (select id from runners where name = 'Patrik Gälman'), null, 'DNC', null),
  ((select id from editions where year = 2012), (select id from runners where name = 'Gabriel Bergqvist'), null, 'DNC', null),
  ((select id from editions where year = 2013), (select id from runners where name = 'Gabriel Bergqvist'), 5, null, 3640),
  ((select id from editions where year = 2014), (select id from runners where name = 'Gabriel Bergqvist'), 4, null, 3881),
  ((select id from editions where year = 2015), (select id from runners where name = 'Gabriel Bergqvist'), null, 'DNC', null),
  ((select id from editions where year = 2016), (select id from runners where name = 'Gabriel Bergqvist'), null, 'DNC', null),
  ((select id from editions where year = 2017), (select id from runners where name = 'Gabriel Bergqvist'), null, 'DNC', null),
  ((select id from editions where year = 2018), (select id from runners where name = 'Gabriel Bergqvist'), null, 'DNC', null),
  ((select id from editions where year = 2019), (select id from runners where name = 'Gabriel Bergqvist'), null, 'DNC', null),
  ((select id from editions where year = 2020), (select id from runners where name = 'Gabriel Bergqvist'), null, 'DNC', null),
  ((select id from editions where year = 2021), (select id from runners where name = 'Gabriel Bergqvist'), null, 'DNC', null),
  ((select id from editions where year = 2022), (select id from runners where name = 'Gabriel Bergqvist'), null, 'DNC', null),
  ((select id from editions where year = 2023), (select id from runners where name = 'Gabriel Bergqvist'), null, 'DNC', null),
  ((select id from editions where year = 2024), (select id from runners where name = 'Gabriel Bergqvist'), null, 'DNC', null),
  ((select id from editions where year = 2025), (select id from runners where name = 'Gabriel Bergqvist'), null, 'DNC', null),
  ((select id from editions where year = 2026), (select id from runners where name = 'Gabriel Bergqvist'), null, 'DNC', null),
  ((select id from editions where year = 2012), (select id from runners where name = 'Magnus Sandén'), 6, null, 3903),
  ((select id from editions where year = 2013), (select id from runners where name = 'Magnus Sandén'), 7, null, 4335),
  ((select id from editions where year = 2014), (select id from runners where name = 'Magnus Sandén'), null, 'DNC', null),
  ((select id from editions where year = 2015), (select id from runners where name = 'Magnus Sandén'), null, 'DNC', null),
  ((select id from editions where year = 2016), (select id from runners where name = 'Magnus Sandén'), null, 'DNC', null),
  ((select id from editions where year = 2017), (select id from runners where name = 'Magnus Sandén'), null, 'DNC', null),
  ((select id from editions where year = 2018), (select id from runners where name = 'Magnus Sandén'), null, 'DNC', null),
  ((select id from editions where year = 2019), (select id from runners where name = 'Magnus Sandén'), null, 'DNC', null),
  ((select id from editions where year = 2020), (select id from runners where name = 'Magnus Sandén'), null, 'DNC', null),
  ((select id from editions where year = 2021), (select id from runners where name = 'Magnus Sandén'), null, 'DNC', null),
  ((select id from editions where year = 2022), (select id from runners where name = 'Magnus Sandén'), null, 'DNC', null),
  ((select id from editions where year = 2023), (select id from runners where name = 'Magnus Sandén'), null, 'DNC', null),
  ((select id from editions where year = 2024), (select id from runners where name = 'Magnus Sandén'), null, 'DNC', null),
  ((select id from editions where year = 2025), (select id from runners where name = 'Magnus Sandén'), null, 'DNC', null),
  ((select id from editions where year = 2026), (select id from runners where name = 'Magnus Sandén'), null, 'DNC', null),
  ((select id from editions where year = 2012), (select id from runners where name = 'Daniel Börjesson'), null, 'DNC', null),
  ((select id from editions where year = 2013), (select id from runners where name = 'Daniel Börjesson'), 4, null, 3507),
  ((select id from editions where year = 2014), (select id from runners where name = 'Daniel Börjesson'), null, 'DNC', null),
  ((select id from editions where year = 2015), (select id from runners where name = 'Daniel Börjesson'), null, 'DNC', null),
  ((select id from editions where year = 2016), (select id from runners where name = 'Daniel Börjesson'), null, 'DNC', null),
  ((select id from editions where year = 2017), (select id from runners where name = 'Daniel Börjesson'), null, 'DNC', null),
  ((select id from editions where year = 2018), (select id from runners where name = 'Daniel Börjesson'), null, 'DNC', null),
  ((select id from editions where year = 2019), (select id from runners where name = 'Daniel Börjesson'), null, 'DNC', null),
  ((select id from editions where year = 2020), (select id from runners where name = 'Daniel Börjesson'), null, 'DNC', null),
  ((select id from editions where year = 2021), (select id from runners where name = 'Daniel Börjesson'), null, 'DNC', null),
  ((select id from editions where year = 2022), (select id from runners where name = 'Daniel Börjesson'), null, 'DNC', null),
  ((select id from editions where year = 2023), (select id from runners where name = 'Daniel Börjesson'), null, 'DNC', null),
  ((select id from editions where year = 2024), (select id from runners where name = 'Daniel Börjesson'), null, 'DNC', null),
  ((select id from editions where year = 2025), (select id from runners where name = 'Daniel Börjesson'), null, 'DNC', null),
  ((select id from editions where year = 2026), (select id from runners where name = 'Daniel Börjesson'), null, 'DNC', null),
  ((select id from editions where year = 2012), (select id from runners where name = 'Johan Jörstun'), 7, null, 4648),
  ((select id from editions where year = 2013), (select id from runners where name = 'Johan Jörstun'), null, 'DNR', null),
  ((select id from editions where year = 2014), (select id from runners where name = 'Johan Jörstun'), null, 'DNC', null),
  ((select id from editions where year = 2015), (select id from runners where name = 'Johan Jörstun'), null, 'DNC', null),
  ((select id from editions where year = 2016), (select id from runners where name = 'Johan Jörstun'), null, 'DNC', null),
  ((select id from editions where year = 2017), (select id from runners where name = 'Johan Jörstun'), null, 'DNC', null),
  ((select id from editions where year = 2018), (select id from runners where name = 'Johan Jörstun'), null, 'DNC', null),
  ((select id from editions where year = 2019), (select id from runners where name = 'Johan Jörstun'), null, 'DNC', null),
  ((select id from editions where year = 2020), (select id from runners where name = 'Johan Jörstun'), null, 'DNC', null),
  ((select id from editions where year = 2021), (select id from runners where name = 'Johan Jörstun'), null, 'DNC', null),
  ((select id from editions where year = 2022), (select id from runners where name = 'Johan Jörstun'), null, 'DNC', null),
  ((select id from editions where year = 2023), (select id from runners where name = 'Johan Jörstun'), null, 'DNC', null),
  ((select id from editions where year = 2024), (select id from runners where name = 'Johan Jörstun'), null, 'DNC', null),
  ((select id from editions where year = 2025), (select id from runners where name = 'Johan Jörstun'), null, 'DNC', null),
  ((select id from editions where year = 2026), (select id from runners where name = 'Johan Jörstun'), null, 'DNC', null)
on conflict (edition_id, runner_id) do nothing;
